### ISSUE TITLE
Browser-sync should refresh upon manuscript source changes

### ISSUE THREAD

**Issue by worlduniting** [worlduniting/bookpub#1]
**Describe the bug**
browser-sync is not refreshing the browser when edits are made to the manuscript source files.

**To Reproduce**
1. Run `npm run dev`
2. Edit one of the manuscript markdown files
3. Browser does not refresh the browser page that was opened upon initial `npm run dev`

**Expected behavior**
When running `npm run dev` and then editing the manuscript markdown source, the browser should be refreshed with the newly generated HTML build.

**Screenshots**
(none)

**Desktop (please complete the following information):**
 - Mac OS
 - Chrome
 - 110.0.5481.177 (Official Build) (x86_64)

**Smartphone (please complete the following information):**
NA

**Additional context**
* Nodemon is triggered and successfully builds the HTML file
* Browser-sync is triggered and says it's refreshing the browser, but nothing happens in the browser.

```
[0] [nodemon] restarting due to changes...
[0] [nodemon] starting `npm run build`
[0] 
[0] > bookshop@1.0.0 build
[0] > node index.mjs
[0] 
[0] HTML file written to /Users/revdavethompson/Projects/bookshop/build/html/index.html
[0] [nodemon] clean exit - waiting for changes before restart
[1] [Browsersync] Reloading Browsers...
```

**Comment by davidandrewthompson** [comment]
It appears that browser-sync is the culprit (sort of).

**Problem**
* Browser-sync refreshes the browser by inserting a script into the HTML file while loading it into the browser. 
* The HTML file needs to be a fully formed html doc (which includes <html> and <body> tags.
* Currently the html that is generated does not have these.

**Solution**
Clearly the HTML tags need to be added, especially since the end result will be to use CSS to style.

Some possible solutions:
* Add the actual tags in the manuscript source and pass them through the pipeline
* Add markdown directives with
  * [remark-directive](https://github.com/remarkjs/remark-directive), or
  * [remark-directive-rehype](https://github.com/IGassmann/remark-directive-rehype)
